### PR TITLE
DAS-2180: Remove Conda dependency on docker images

### PR DESCRIPTION
**Pull request by flamingbear**
-------

## Description

Remove conda dependency from HyBIG

Updates the docker images to use `python:3.11` instead of `continuumio/miniconda3` and removes `conda` commands and environment

## Jira Issue ID

[DAS-2180](https://bugs.earthdata.nasa.gov/browse/DAS-2180)

## Local Test Steps

Pull branch, build and deploy to Harmony-In-A-Box

``` shell
./bin/build-image && ./bin/build-test && ./bin/run-test
```

Make sure unit tests pass.

Run regression tests against the local image.

## PR Acceptance Checklist
* [N/A] Jira ticket acceptance criteria met.
* [x] `CHANGELOG.md` updated to include high level summary of PR changes.
* [x] `docker/service_version.txt` updated if publishing a release.
* [N/A] Tests added/updated and passing.
* [N/A] Documentation updated (if needed).

### CODE REVIEW

**Comment by flamingbear** [comment]
So b854d46 may be the worst commit I've ever done.  All it does is move the uninstallable snyk package into the file that is ignored in snyk. And confusingly still calls it all conda when it's all pip.

**Review by owenlittlejohns — CHANGES_REQUESTED** [review]
First up - I _love_ the migration to a single package manager, this is great.

As discussed in Slack I am concerned about this change preventing us from scanning any dependencies in Snyk, because it can't install `gdal` when scanning. I think we landed on your alternative, which was to put the `gdal` dependency in a separate file, which Snyk doesn't scan. Kind of ugly, but I think that gets us to a better place overall. We were trying to come up with a good file name. How about: `pip_requirements_non_snyk.txt` (not particularly great, but :shrug:). Probably would be good to add prose to the README and the top of that file just explaining why it exists, and how/when it might be removable.

Also noting that `pip install` can support multiple files via `-r` in the same command for when you add that to this PR.

**Comment by flamingbear** [comment]
@owenlittlejohns I think this is ready for re-review.

**Review by owenlittlejohns — APPROVED** [review]
Nice! I do like some of the things this work has enabled the removal off - like those environment variables that were set to activate the conda environment (while continuing to allow log streaming).

**Pull request merged**
